version: '3.8'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static/:/usr/share/nginx/html/static/
      - ./app/media/:/usr/share/nginx/html/media/
    ports:
      - 80:80
    depends_on:
      - django
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  daphne:
    build: ./app
    command: daphne -b 0.0.0.0 -p 8001 hello_django.asgi:application
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
    depends_on:
      - django

volumes:
  postgres_data:

