version: '3.8'

services:
  django:
    build: ./app
    command: python manage.py runserver
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - django
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432:5432

volumes:
  postgres_data:

