version: '3.8'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app/static/:/usr/share/nginx/html/static/
      - ./app/media/:/usr/share/nginx/html/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  adminer:
     image: adminer
     restart: always
     ports:
       - "8080:8080"

volumes:
  postgres_data:
