# pull official base image
FROM python:3.13.0rc2-slim

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install djangorestframework
RUN python -m pip install Pillow
#  bibliothèque Python 'channels' pour gérer les connexions WebSocket dans Django
RUN python -m pip install channels channels_redis daphne

RUN pip install django-two-factor-auth
RUN pip install django-two-factor-auth[phonenumbers]
RUN pip install django-otp-yubikey
RUN pip install django-two-factor-auth[webauthn]
RUN pip install djangorestframework-jwt
RUN pip install django-qr-code pillow

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

EXPOSE 8000

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

