# Generated by Django 4.2.3 on 2024-03-11 15:26

import django.contrib.auth.validators
from django.db import migrations, models
import hello_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_tournament', models.PositiveIntegerField(default=0)),
                ('date_tournament', models.DateTimeField(blank=True, null=True)),
                ('player1', models.CharField(max_length=12, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('player2', models.CharField(max_length=12, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('player3', models.CharField(max_length=12, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('player4', models.CharField(max_length=12, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('match1', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('match2', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('match3', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('result1', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('result2', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('result3', models.CharField(max_length=25, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
            ],
            options={
                'db_table': 'django_tournament',
            },
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=12, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('password', models.CharField(max_length=128, validators=[hello_django.models.validate_password_length])),
                ('email', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(default='photos/default-profile.jpg', upload_to='photos/')),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('in_game', 'En jeu')], default='offline', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('double_auth', models.BooleanField(default=0)),
                ('last_tournament_position', models.PositiveIntegerField(default=0)),
                ('last_tournament_date', models.DateTimeField(blank=True, null=True)),
                ('last_match_tournament_result', models.CharField(max_length=15)),
                ('last_match_tournament_opponent', models.CharField(max_length=15)),
                ('user_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'django_user_list',
            },
        ),
    ]
