# Generated by Django 4.2.3 on 2024-03-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournament', models.DateTimeField(blank=True, null=True)),
                ('player01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player01_tournaments', to='hello_django.user_list')),
                ('player02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player02_tournaments', to='hello_django.user_list')),
                ('player03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player03_tournaments', to='hello_django.user_list')),
                ('player04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player04_tournaments', to='hello_django.user_list')),
            ],
            options={
                'db_table': 'django_tournament',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'En attente de joueurs'), ('end_game', 'Fin de partie'), ('in_game', 'En jeu')], default='waiting', max_length=20)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='hello_django.user_list')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='hello_django.user_list')),
                ('player_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_matches', to='hello_django.user_list')),
            ],
        ),
    ]
