# Generated by Django 4.2.3 on 2024-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_list',
            name='score',
        ),
        migrations.AddField(
            model_name='user_list',
            name='intra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
