# Generated by Django 4.2.3 on 2024-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
