# Generated by Django 4.2.3 on 2024-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0002_user_list_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='double_auth',
            field=models.BooleanField(default=1),
        ),
    ]
